(define-module (tay home-common)
  #:use-module (gnu home services)
  #:use-module (gnu home services dotfiles)
  #:use-module (gnu home services fontutils)
  #:use-module (gnu home services gnupg)
  #:use-module (gnu home services shells)
  #:use-module (gnu home services shepherd)
  #:use-module (gnu packages)
  #:use-module (gnu services)
  #:use-module (gnu services shepherd)
  #:use-module (guix gexp)
  #:export (%primary-font
            %core-home-packages
            %core-home-services))

(define %dotfiles-directory "/home/tay/src/dotfiles")
(define %guix-config-directory "/home/tay/src/guix-config")
(define %primary-font "unscii")
(define (dotfile path)
  (string-append %dotfiles-directory "/" path))
(define (guix-config-file path)
  (string-append %guix-config-directory "/" path))

(define (generated-stumpwmrc)
  (let ((source (local-file (dotfile "stumpwm/.stumpwmrc")
                            "stumpwmrc-source"))
         (prelude (string-append
                   "(in-package :stumpwm)\n"
                   "(run-shell-command \". /home/tay/.xprofile; xrdb -merge /home/tay/.Xresources; host_resources=/home/tay/.Xresources.host-$(hostname); test ! -r \\\"$host_resources\\\" || xrdb -merge \\\"$host_resources\\\"\" t)\n"
                   "(update-modifier-map)\n"
                   "(sync-keys)\n"
                   "(run-shell-command \"xset s off\")\n"
                   "(run-shell-command \"xset +dpms\")\n"
                   "(run-shell-command \"xset dpms 0 0 600\")\n"
                   "(defparameter *tay-primary-font-family* \""
                   %primary-font
                   "\")\n")))
    (computed-file
     "stumpwmrc"
     #~(begin
         (use-modules (ice-9 textual-ports))
         (call-with-output-file #$output
           (lambda (output)
             (display #$prelude output)
             (call-with-input-file #$source
               (lambda (input)
                 (display (get-string-all input) output)))))))))

(define (generated-kitty-config)
  (let ((source (local-file (dotfile "config/.config/kitty/kitty.conf")
                            "kitty-conf-source"))
        (prelude (string-append
                  "# Generated by Guix Home; edit the source body under ~/src/dotfiles.\n"
                  "# Pin every face to the native Unscii 16-pixel PCF strike.\n"
                  "font_family family=\"" %primary-font "\" style=full\n"
                  "bold_font family=\"" %primary-font "\" style=full\n"
                  "italic_font family=\"" %primary-font "\" style=full\n"
                  "bold_italic_font family=\"" %primary-font "\" style=full\n\n")))
    (computed-file
     "kitty.conf"
     #~(begin
         (use-modules (ice-9 textual-ports))
         (call-with-output-file #$output
           (lambda (output)
             (display #$prelude output)
             (call-with-input-file #$source
               (lambda (input)
                 (display (get-string-all input) output)))))))))

(define (kanata-service provision file-name device-name)
  (let* ((service-name (symbol->string provision))
         (provisions (list provision))
         (config (local-file (dotfile file-name) service-name))
         (kanata (file-append (specification->package "kanata")
                              "/bin/kanata"))
         (launcher
          (program-file
           (string-append service-name "-launcher")
           #~(begin
               (use-modules (ice-9 textual-ports)
                            (srfi srfi-13))
               (let wait-for-device ()
                 (if (and (file-exists? "/proc/bus/input/devices")
                          (string-contains
                           (call-with-input-file "/proc/bus/input/devices"
                             get-string-all)
                           #$device-name))
                     (execl #$kanata #$kanata "-c" #$config)
                     (begin
                       (sleep 60)
                       (wait-for-device))))))))
    (shepherd-service
     (documentation (string-append "Run Kanata profile " service-name "."))
     (provision provisions)
     (modules '((shepherd support)))
      (start #~(make-forkexec-constructor
                (list #$launcher)
                #:log-file
                (string-append %user-log-dir "/"
                               #$service-name ".log")))
      (stop #~(make-kill-destructor)))))

(define %fontconfig-rules
  '((dir "~/.local/share/fonts")
    ;; Synthesize oblique faces when a font has no italic variant.
    (match (@ (target "font"))
      (test (@ (name "slant"))
        (const "roman"))
      (test (@ (compare "not_eq") (name "slant") (target "pattern"))
        (const "roman"))
      (edit (@ (mode "assign") (name "matrix"))
        (times
          (name "matrix")
          (matrix
            (double "1")
            (double "0.2")
            (double "0")
            (double "1"))))
      (edit (@ (mode "assign") (name "slant"))
        (const "oblique"))
      (edit (@ (mode "assign") (name "embeddedbitmap"))
        (bool "false")))
    ;; Synthesize bold faces when a font has no bold variant.
    (match (@ (target "font"))
      (test (@ (compare "less_eq") (name "weight"))
        (const "medium"))
      (test (@ (compare "more_eq") (name "weight") (target "pattern"))
        (const "bold"))
      (edit (@ (mode "assign") (name "embolden"))
        (bool "true"))
      (edit (@ (mode "assign") (name "weight"))
        (const "bold")))
    (match (@ (target "font"))
      (edit (@ (mode "assign") (name "hinting"))
        (bool "true")))
    (match (@ (target "font"))
      (edit (@ (mode "assign") (name "hintstyle"))
        (const "hintslight")))
    (match (@ (target "font"))
      (edit (@ (mode "assign") (name "antialias"))
        (bool "true")))
    ;; Keep bitmap-derived Unscii crisp in Xft clients such as xterm.
    (match (@ (target "font"))
      (test (@ (compare "eq") (name "family"))
        (string "unscii"))
      (edit (@ (mode "assign") (name "antialias"))
        (bool "false"))
      (edit (@ (mode "assign") (name "hinting"))
        (bool "false")))
    ;; Same treatment for the CADR, Genera, and DEC bitmap families. These
    ;; ship many families each ("MIT CADR Gacha", "Symbolics Genera Math",
    ;; ...), so match on the shared prefix with `contains' rather than
    ;; enumerating every face. The DEC VT220 fonts use the family "vt220".
    (match (@ (target "font"))
      (test (@ (compare "contains") (name "family"))
        (string "MIT CADR"))
      (edit (@ (mode "assign") (name "antialias"))
        (bool "false"))
      (edit (@ (mode "assign") (name "hinting"))
        (bool "false")))
    (match (@ (target "font"))
      (test (@ (compare "contains") (name "family"))
        (string "Symbolics Genera"))
      (edit (@ (mode "assign") (name "antialias"))
        (bool "false"))
      (edit (@ (mode "assign") (name "hinting"))
        (bool "false")))
    (match (@ (target "font"))
      (test (@ (compare "eq") (name "family"))
        (string "vt220"))
      (edit (@ (mode "assign") (name "antialias"))
        (bool "false"))
      (edit (@ (mode "assign") (name "hinting"))
        (bool "false")))))

(define %core-home-packages
  (specifications->packages
   '("kanata"
     "age"
     "jq"
     "sops"
     "gnupg"
      "stumpish"
      "xrdb"
      "xkbcomp"
      "xsetroot"
      "node"
     "python"
     "python-pyxdg"
     "sbcl-cl-diskspace"
     "sbcl-cl-mount-info"
     "sbcl-cl-ppcre"
     "sbcl-clx-xembed"
     "sbcl-py-configparser"
     "sbcl-stumpwm-hostname"
     "sbcl-stumpwm-disk"
     "sbcl-stumpwm-mem"
     "sbcl-stumpwm-stumptray")))

(define %core-home-services
  (list
   (simple-service
    'sops-age-key
    home-environment-variables-service-type
    `(("SOPS_AGE_KEY_FILE" . "$HOME/.config/sops/age/keys.txt")))
   ;; Point Pi's okf-knowledge extension at the real OKF bundle container in
   ;; ~/okf instead of its ~/.pi/agent/knowledge default, matching the
   ;; OpenCode/omo `references` entries. Set here rather than in a bashrc
   ;; fragment so non-interactive shells and GUI-launched processes see it.
   (simple-service
    'okf-knowledge-root
    home-environment-variables-service-type
    `(("PI_OKF_GLOBAL_ROOT" . "$HOME/okf")))
   ;; Xt looks for app-defaults under the compiled-in system prefix, which on
   ;; Guix never contains the home profile. Without this, xfontsel, xfd, and
   ;; xterm warn "app-defaults file not properly installed" and fall back to
   ;; built-in defaults, losing widget labels, layout constraints, and sizing.
   (simple-service
    'xt-app-defaults
    home-environment-variables-service-type
    `(("XFILESEARCHPATH"
       . "$HOME/.guix-home/profile/lib/X11/app-defaults/%N")))
   ;; Extend Guix Home's essential Fontconfig service rather than replacing
   ;; the fonts.conf it owns.
   (simple-service
    'tay-fontconfig-rules
    home-fontconfig-service-type
    %fontconfig-rules)
   (service home-gpg-agent-service-type
            (home-gpg-agent-configuration
             (default-cache-ttl 86400)
             (max-cache-ttl 86400)
             (extra-content "allow-preset-passphrase\n")))
   (service home-bash-service-type
            (home-bash-configuration
             (guix-defaults? #t)
             (bashrc
              (list (local-file (dotfile "home/.bashrc") "bashrc")))
             (bash-profile
              (list (local-file (dotfile "home/.bash_profile")
                                "bash-profile")))))
   (service home-dotfiles-service-type
            (home-dotfiles-configuration
             (source-directory %dotfiles-directory)
             (layout 'stow)
             (directories '("."))
             (packages '("home" "x11" "stumpwm" "config" "keyboard"
                         "emacs" "clawmacs" "claude" "pi" "gnupg"))
             (excluded
               '(".*~"
                 ".*\\.swp"
                 ".*[^A-Za-z0-9+._?/-].*"
                 ".*:.*"
                ".*@.*"
                "/\\.git/.*"
                "/node_modules/.*"
                "\\.gitignore"
                "/\\.stow-local-ignore$"
                "/home/\\.bashrc$"
                 "/home/\\.bash_profile$"
                 "/stumpwm/\\.stumpwmrc$"
                 ;; Codex rewrites this file in place when you trust a
                 ;; project or change a setting, and it deliberately follows
                 ;; symlinks to their final target before writing. A store
                 ;; symlink therefore makes it try to write into /gnu/store
                 ;; and fail. Leave it as a real file under ~/.codex; the
                 ;; tracked copy in dotfiles is the seed/backup.
                 "/home/\\.codex/config\\.toml$"
                 ;; Deployed whole-directory below instead. ASDF resolves a
                 ;; system's components relative to the truename of its .asd,
                 ;; and per-file store symlinks resolve straight into
                 ;; /gnu/store, so it would look for package.lisp in
                 ;; /gnu/store/ and fail.
                 "/stumpwm/\\.stumpwm\\.d/modules/.*"
                 ;; These paths are owned by native Guix Home services.
                 "/config/\\.config/fontconfig/fonts\\.conf$"
                 "/config/\\.config/kitty/kitty\\.conf$"
                 "/gnupg/\\.gnupg/gpg-agent\\.conf$"
                 "/config/\\.config/sunshine/credentials/cakey\\.pem$"
                 "/config/\\.config/sunshine/sunshine_state\\.json$"
                 "/config/\\.config/shepherd/.*"
                 "/config/\\.config/systemd/.*"))))
   (simple-service
    'guix-channel-config
    home-xdg-configuration-files-service-type
    `(("guix/channels.scm"
       ,(local-file (guix-config-file "channels.scm") "guix-channels.scm"))
      ;; Trust the same authenticated channel introductions used by pulls.
      ("guix/trusted-channels.scm"
       ,(local-file (guix-config-file "channels.scm")
                    "guix-trusted-channels.scm"))))
   (simple-service
    'generated-kitty-config
    home-xdg-configuration-files-service-type
    `(("kitty/kitty.conf" ,(generated-kitty-config))))
   (simple-service
    'generated-stumpwmrc
    home-files-service-type
    `((".stumpwmrc" ,(generated-stumpwmrc))))
   ;; Re-apply the Space Cadet XKB keymap after every activation.
   ;;
   ;; Guix Home activation replaces ~/.config/xkb wholesale with new store
   ;; symlinks, but the running X server keeps the keymap it compiled at
   ;; session start. The files change underneath it and nothing reloads them,
   ;; so after a reconfigure the layout silently reverts to stock us: RALT
   ;; goes back to ISO_Level3_Shift (AltGr) instead of the Alt_L that the
   ;; window manager binds, and Mod3/Mod5 no longer match the layout.
   ;;
   ;; The helper is a no-op when no X display is reachable, so this stays
   ;; safe on headless reconfigures.
   ;; Vendored StumpWM modules, deployed as whole directories so ASDF can
   ;; resolve each system's components next to its .asd file.
   (simple-service
    'vendored-stumpwm-modules
    home-files-service-type
    `((".stumpwm.d/modules/desktop-entry"
       ,(local-file (dotfile "stumpwm/.stumpwm.d/modules/desktop-entry")
                    "stumpwm-desktop-entry"
                    #:recursive? #t))))
   (simple-service
    'reload-spacecadet-xkb
    home-activation-service-type
    #~(system*
       #$(local-file (dotfile "keyboard/manna-cadet/reload-spacecadet-xkb.sh")
                     "reload-spacecadet-xkb.sh"
                     #:recursive? #t)))
   (simple-service
    'kanata
    home-shepherd-service-type
    (list
      (kanata-service
       'kanata-advantage360
       "keyboard/manna-cadet/kanata/kinesis.advantage360.layered.kanata.kbd"
       "Kinesis Kinesis Adv360")
      (kanata-service
       'kanata-footswitches
       "keyboard/footswitches.kanata.kbd"
       "PCsensor FootSwitch Keyboard")))))
