creation_rules:
  - path_regex: secrets/.*\.sops\.yaml$
    age: age1l5lqrpwafa8zq9nclkflhr3nfk00drmkuqdhqwgn0z7hucmjm4ssd965k6,age1m7jhw4zqz7eatrtg9jnyz2ayu0xefpt9qs25z7rhx2gydfq42dgszk4j75,age1395kcwh89rgv0jr854dsc463e3vvvdrmjruhjg37kx3kksced9xstd8uj0
