[General]
bgColor=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
fallbackIconTheme=oxygen
fullScreenBgColor=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
maxRecentFiles=5
recentlyOpenedFiles=/home/tay/2026-04-29-004337_768x963_scrot.png, /home/tay/2026-04-29-004638_768x963_scrot.png, /home/tay/2026-01-29-021246_2152x1419_scrot.png, /home/tay/2026-03-31-150314_905x658_scrot.png, /home/tay/2026-03-29-164213_1704x1419_scrot.png
slideShowInterval=5
solidBg=true
sorting=name

[Thumbnail]
MaxThumbnailFileSize=4096
ShowThumbnails=false
ThumbnailSize=64
ThumbnailsPosition=bottom

[Window]
ColorSpace=1
ExifDatakWidth=250
FixedHeight=480
FixedWidth=640
ForceZoomFit=false
LastWindowHeight=598
LastWindowMaximized=false
LastWindowWidth=798
PrefSize=@Size(400 400)
ShowAnnotationsToolbar=false
ShowExifData=false
ShowMenubar=true
ShowOutline=false
ShowToolbar=true
SmoothOnZoom=true
UseTrash=true
