import type { CustomGraphSettings } from "./schema";

export const PACKAGED_CUSTOM_GRAPH_PRESETS = {
  "common-lisp-asdf": {
    description: "Common Lisp ASDF/package/API/library workflow with SBCL/ASDF/FiveAM fallback validation.",
    stages: [
      {
        id: "discover",
        kind: "PLAN",
        title: "Discover ASDF project shape and commands",
        description: "Discover ASDF system files, package definitions, public API boundaries, test systems, and project validation commands before editing.",
        descriptor: {
          stableKey: "custom.common-lisp-asdf.discover",
          purpose: "Discover ASDF systems, packages, tests, and project validation commands before editing.",
          inputs: ["User Common Lisp ASDF task", "Project files, README, CI scripts, and .asd files"],
          outputs: ["Discovered system/package/test shape", "Project-specific validation command candidates"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["ASDF systems, packages, tests, and commands are identified", "No implementation files are edited during discovery"],
          writeScope: ["read-only discovery notes"],
          isolationBoundary: ["Stay read-only", "Record uncertainty instead of inventing project facts"],
        },
        runnerKind: "chain",
        runnerName: "general-dev-plan",
        sideEffects: "read",
        skills: ["common-lisp-task-graphs", "build-test-procedures", "common-lisp"],
        promptInstructions: [
          "Inspect the project before editing. Identify .asd files, defsystem forms, package/defpackage files, README/CI/Makefile scripts, and existing validation commands.",
          "Prefer discovered project commands over generic examples. If nothing is discoverable, fall back to SBCL plus ASDF load/test commands using the discovered system name.",
          "Do not assume Quicklisp is present unless the project already uses it.",
          "Record evidence: discovered ASDF system files, inferred system names, package/export files, test systems, and exact validation commands or why none were found.",
        ],
      },
      {
        id: "api-contract",
        kind: "PLAN",
        title: "Define package/API contract",
        description: "Clarify public package and API impact before implementation, including exported symbols and compatibility expectations.",
        descriptor: {
          stableKey: "custom.common-lisp-asdf.api-contract",
          purpose: "Define the package/API contract and compatibility expectations before implementation.",
          inputs: ["Discovery findings", "User-requested public behavior"],
          outputs: ["Public API/package contract", "Export/documentation/test synchronization notes"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Public behavior and exports are explicit", "Compatibility risks are named before implementation"],
          writeScope: ["read-only planning notes"],
          isolationBoundary: ["Do not edit implementation files", "Do not change public compatibility assumptions silently"],
        },
        dependsOn: ["discover"],
        runnerKind: "chain",
        runnerName: "general-dev-plan",
        sideEffects: "read",
        skills: ["common-lisp-task-graphs", "common-lisp"],
        promptInstructions: [
          "Check defpackage forms, exports, internal/private symbols, naming conventions, ASDF component lists, and test-system wiring before editing.",
          "For a library change, state what public behavior is added or changed and which package exports or documentation need updates.",
          "Keep backward compatibility explicit. If changing existing exported behavior is required, call it out as a risk before implementation.",
        ],
      },
      {
        id: "implement",
        kind: "IMPLEMENT",
        title: "Implement bounded Common Lisp change",
        description: "Make the smallest ASDF/package/library implementation change while keeping systems, packages, exports, and tests synchronized.",
        descriptor: {
          stableKey: "custom.common-lisp-asdf.implement",
          purpose: "Implement the bounded Common Lisp ASDF/package/API change.",
          inputs: ["API contract", "Discovered validation commands", "Current Lisp source and tests"],
          outputs: ["Synchronized code, packages, ASDF components, docs, and tests"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Code, packages, exports, ASDF components, and tests remain synchronized", "Focused validation evidence is recorded"],
          writeScope: ["*.asd", "**/*.asd", "**/*.lisp", "test/**", "tests/**"],
          isolationBoundary: ["Stay within the requested Common Lisp change", "Avoid broad rewrites and dependency assumptions"],
        },
        dependsOn: ["api-contract"],
        subagentType: "implementer",
        sideEffects: "write",
        skills: ["common-lisp-task-graphs", "build-test-procedures", "tdd", "implementer", "common-lisp"],
        expectedWritePaths: ["*.asd", "**/*.asd", "**/*.lisp", "test/**", "tests/**"],
        promptInstructions: [
          "Use TDD for observable behavior changes when a test harness exists. Add or update focused Lisp tests near the changed behavior first, then implement minimally.",
          "Keep package definitions, ASDF components, exported symbols, documentation snippets, and tests synchronized with the code change.",
          "Avoid broad rewrites, reader-macro surprises, global state changes, or Quicklisp assumptions unless the project already uses them and the user requested the change.",
        ],
      },
      {
        id: "compile-load",
        kind: "COMPILE",
        title: "Validate ASDF load/compile",
        description: "Run discovered compile/load checks; if needed, use SBCL/ASDF load-system or compile-system examples as fallbacks.",
        descriptor: {
          stableKey: "custom.common-lisp-asdf.compile-load",
          purpose: "Validate ASDF load/compile behavior with discovered or safe fallback commands.",
          inputs: ["Implementation diff", "Discovered compile/load commands"],
          outputs: ["Compile/load command evidence", "Actionable file/form failures when present"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Discovered commands or safe ASDF fallback were attempted", "Failures are classified with actionable context"],
          writeScope: ["validation report only"],
          isolationBoundary: ["Do not edit product files in compile verification", "Prefer project commands before generic fallbacks"],
        },
        dependsOn: ["implement"],
        subagentType: "compile-verifier",
        sideEffects: "shell",
        skills: ["common-lisp-task-graphs", "build-test-procedures", "compile-verifier", "common-lisp"],
        promptInstructions: [
          "Run the project's discovered build, load, or compile commands first and capture exact commands plus output.",
          "If no project command exists, use a discovered system name with a fallback such as: sbcl --noinform --disable-debugger --eval '(require \"asdf\")' --eval '(asdf:load-system \"SYSTEM-NAME\")' --quit",
          "When compile-system is appropriate for the project, use the same SBCL/ASDF pattern with asdf:compile-system. Report actionable package, reader, dependency, or compile warnings with file and form context when available.",
        ],
      },
      {
        id: "tests",
        kind: "UNIT_TEST",
        title: "Run ASDF/FiveAM tests",
        description: "Run discovered Common Lisp tests; if needed, use ASDF test-system or FiveAM-oriented commands as fallbacks.",
        descriptor: {
          stableKey: "custom.common-lisp-asdf.tests",
          purpose: "Run Common Lisp unit/test-system checks and record evidence.",
          inputs: ["Compile/load result", "Discovered test commands"],
          outputs: ["Test command evidence", "Failure classification if tests fail"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Project tests or safe fallback test-system command were run", "Failed assertions are treated as code failures"],
          writeScope: ["validation report only"],
          isolationBoundary: ["Do not edit product files in test verification", "Do not hide failed test-system exits"],
        },
        dependsOn: ["compile-load"],
        subagentType: "unit-tester",
        sideEffects: "shell",
        skills: ["common-lisp-task-graphs", "build-test-procedures", "unit-tester", "common-lisp"],
        promptInstructions: [
          "Run the project's discovered test commands first, including Makefile/CI scripts, ASDF test operations, or test-system entrypoints.",
          "If no project command exists, use a discovered system name with a fallback such as: sbcl --noinform --disable-debugger --eval '(require \"asdf\")' --eval '(asdf:test-system \"SYSTEM-NAME\")' --quit",
          "When the project uses FiveAM, prefer the project's existing FiveAM runner or ASDF test operation. Treat failed assertions and unsuccessful test-system exits as code failures, not environmental noise.",
        ],
      },
      {
        id: "review",
        kind: "CODE_REVIEW",
        title: "Review Lisp API and validation evidence",
        description: "Review the ASDF/package/API diff, synchronization across systems/packages/tests, and recorded validation evidence.",
        descriptor: {
          stableKey: "custom.common-lisp-asdf.review",
          purpose: "Review the Lisp API/package diff and validation evidence.",
          inputs: ["Implementation diff", "Validation evidence", "API contract"],
          outputs: ["Prioritized review findings or PASS report"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Package/API synchronization is reviewed", "Validation evidence is sufficient or gaps are reported"],
          writeScope: ["review report only"],
          isolationBoundary: ["Do not edit files during review", "Do not commit or push"],
        },
        dependsOn: ["tests"],
        subagentType: "code-review-enforcer",
        sideEffects: "read",
        skills: ["common-lisp-task-graphs", "code-review", "common-lisp"],
        promptInstructions: [
          "Review public API/package changes, ASDF component/test wiring, exported symbol compatibility, error handling, and test evidence.",
          "Confirm the report lists changed files, exact validation commands, command outputs or failures, and remaining risks. Do not commit or push.",
        ],
      },
    ],
  },
  "common-lisp-clim-tui": {
    description: "Common Lisp CLIM/TUI visible behavior workflow for CLIM, McCLIM, terminal UI, and render-loop-safe changes.",
    stages: [
      {
        id: "discover-ui",
        kind: "PLAN",
        title: "Discover UI entrypoints and behavior",
        description: "Identify CLIM/McCLIM/TUI framework, launch path, panes/commands/renderers, ASDF systems, and visible behavior to preserve.",
        descriptor: {
          stableKey: "custom.common-lisp-clim-tui.discover-ui",
          purpose: "Discover UI framework, entrypoints, launch paths, and visible behavior to preserve.",
          inputs: ["User CLIM/TUI task", "Project ASDF/UI source and docs"],
          outputs: ["UI entrypoint map", "Launch/validation command candidates", "Visible behavior notes"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Framework and launch path are identified or uncertainty is recorded", "Visible behavior to preserve is stated"],
          writeScope: ["read-only discovery notes"],
          isolationBoundary: ["Stay read-only", "Do not invent fragile UI launch commands"],
        },
        runnerKind: "chain",
        runnerName: "general-dev-plan",
        sideEffects: "read",
        skills: ["common-lisp-task-graphs", "build-test-procedures", "common-lisp", "mcclim-manual", "clim-spec"],
        promptInstructions: [
          "Identify the UI framework and launch path before editing: CLIM, McCLIM, terminal UI, curses-like UI, custom REPL UI, or mixed mode.",
          "Locate ASDF systems, entrypoint functions, scripts, frame definitions, panes/layouts/commands, presentation translators, terminal renderers, and existing GUI/TUI tests.",
          "Prefer discovered launch and validation commands. If none exist, record the entrypoint uncertainty instead of inventing a fragile live UI command.",
        ],
      },
      {
        id: "visible-invariant",
        kind: "UX_REVIEW",
        title: "State visible behavior invariant",
        description: "Define the visible behavior invariant for the CLIM/McCLIM/TUI change before implementation.",
        descriptor: {
          stableKey: "custom.common-lisp-clim-tui.visible-invariant",
          purpose: "State the visible behavior invariant before implementation.",
          inputs: ["UI discovery findings", "User-visible change request"],
          outputs: ["Visible behavior invariant and validation strategy"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Invariant covers layout, commands, input/focus, and redraw/terminal behavior as applicable", "Validation strategy is deterministic or gaps are explicit"],
          writeScope: ["read-only UX/planning notes"],
          isolationBoundary: ["Do not edit implementation files", "Prefer framework-native UI mechanisms"],
        },
        dependsOn: ["discover-ui"],
        subagentType: "ux-review-enforcer",
        sideEffects: "read",
        skills: ["common-lisp-task-graphs", "ux-review", "mcclim-manual", "clim-spec"],
        promptInstructions: [
          "Before implementation, state what must remain visibly true after the change: layout, command availability, presentation interaction, focus/input behavior, redraw/redisplay behavior, and terminal output boundaries.",
          "For CLIM/McCLIM, prefer canonical frame, pane, command, presentation, accept, and redisplay mechanisms. Do not replace the app with private render loops, manual sheet/medium manipulation, or coordinate-only hit testing unless the project already requires that workaround and the reason is recorded.",
          "For terminal UIs, preserve a clear state/update/render boundary where present and identify a deterministic capture strategy.",
        ],
      },
      {
        id: "implement-ui",
        kind: "IMPLEMENT",
        title: "Implement bounded UI change",
        description: "Make the smallest CLIM/McCLIM/TUI change while preserving the visible behavior invariant and launch paths.",
        descriptor: {
          stableKey: "custom.common-lisp-clim-tui.implement-ui",
          purpose: "Implement the bounded CLIM/McCLIM/TUI change while preserving the visible invariant.",
          inputs: ["Visible behavior invariant", "Discovered launch and validation commands", "Current UI source/tests"],
          outputs: ["Small UI implementation diff", "Updated tests/docs when needed"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Visible invariant remains satisfied", "Launch paths and framework-native boundaries are preserved"],
          writeScope: ["*.asd", "**/*.asd", "**/*.lisp", "test/**", "tests/**"],
          isolationBoundary: ["Stay within the requested UI change", "Avoid broad render-loop rewrites"],
        },
        dependsOn: ["visible-invariant"],
        subagentType: "implementer",
        sideEffects: "write",
        skills: ["common-lisp-task-graphs", "build-test-procedures", "tdd", "implementer", "common-lisp", "mcclim-manual", "clim-spec"],
        expectedWritePaths: ["*.asd", "**/*.asd", "**/*.lisp", "test/**", "tests/**"],
        promptInstructions: [
          "Make the smallest UI change that satisfies the request while preserving the visible behavior invariant and existing launch commands.",
          "Prefer framework-native panes, gadgets, commands, presentations, and redisplay for CLIM/McCLIM. Prefer deterministic state/update/render seams for TUI code.",
          "Avoid broad UI rewrites or unvalidated render-loop changes. If a workaround is necessary, document why the project requires it.",
        ],
      },
      {
        id: "compile-load",
        kind: "COMPILE",
        title: "Compile/load UI system",
        description: "Run discovered ASDF/SBCL compile or load checks for the UI system before visible behavior validation.",
        descriptor: {
          stableKey: "custom.common-lisp-clim-tui.compile-load",
          purpose: "Compile/load the UI system before visible behavior validation.",
          inputs: ["UI implementation diff", "Discovered compile/load commands"],
          outputs: ["Compile/load evidence", "Environment/code failure classification"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Discovered commands or safe ASDF fallback were attempted", "Display-environment failures are separated from code failures"],
          writeScope: ["validation report only"],
          isolationBoundary: ["Do not edit product files in compile verification", "Keep GUI environment limitations explicit"],
        },
        dependsOn: ["implement-ui"],
        subagentType: "compile-verifier",
        sideEffects: "shell",
        skills: ["common-lisp-task-graphs", "build-test-procedures", "compile-verifier", "common-lisp"],
        promptInstructions: [
          "Run discovered project compile/load commands first and capture exact commands plus output.",
          "If no project command exists, use a discovered system name with an SBCL/ASDF fallback such as: sbcl --noinform --disable-debugger --eval '(require \"asdf\")' --eval '(asdf:load-system \"SYSTEM-NAME\")' --quit",
          "For GUI systems, separate compile/load failures from display-server or terminal-environment failures so follow-up work is routed correctly.",
        ],
      },
      {
        id: "tests",
        kind: "UNIT_TEST",
        title: "Run Common Lisp UI tests",
        description: "Run discovered tests for CLIM/McCLIM/TUI behavior, with ASDF test-system or FiveAM fallbacks when appropriate.",
        descriptor: {
          stableKey: "custom.common-lisp-clim-tui.tests",
          purpose: "Run discovered Common Lisp UI tests or safest available fallbacks.",
          inputs: ["Compile/load result", "Discovered UI test commands"],
          outputs: ["UI test evidence", "Failure classification"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Existing tests or safe smoke/load checks were run", "Failures are classified as code, display, terminal, dependency, or operator setup"],
          writeScope: ["validation report only"],
          isolationBoundary: ["Do not edit product files in test verification", "Do not overstate smoke checks as full UI proof"],
        },
        dependsOn: ["compile-load"],
        subagentType: "unit-tester",
        sideEffects: "shell",
        skills: ["common-lisp-task-graphs", "build-test-procedures", "unit-tester", "common-lisp"],
        promptInstructions: [
          "Run existing project tests first, including ASDF test-system, FiveAM suites, terminal renderer tests, or smoke scripts discovered during planning.",
          "If no test command exists, report that gap and run only the safest load/smoke command that the project structure supports.",
          "Classify failures as code, display-environment, terminal-environment, dependency, or operator setup so UI validation can proceed safely.",
        ],
      },
      {
        id: "visible-validation",
        kind: "UX_REVIEW",
        title: "Validate visible behavior",
        description: "Validate CLIM/McCLIM/TUI visible behavior with deterministic screenshots, logs, terminal captures, or project-specific UI checks.",
        descriptor: {
          stableKey: "custom.common-lisp-clim-tui.visible-validation",
          purpose: "Validate visible CLIM/McCLIM/TUI behavior with deterministic artifacts when available.",
          inputs: ["Visible behavior invariant", "Test results", "Launch/capture commands"],
          outputs: ["Screenshot, log, terminal capture, or documented smoke evidence"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Visible behavior evidence is recorded or environment limits are explicit", "Commands and artifact paths are included"],
          writeScope: ["visible validation artifacts only"],
          isolationBoundary: ["Do not edit product files during visible validation", "Avoid unsafe live UI automation without project support"],
        },
        dependsOn: ["tests"],
        subagentType: "ux-review-enforcer",
        sideEffects: "shell",
        skills: ["common-lisp-task-graphs", "ux-review", "e2e-test", "mcclim-manual", "clim-spec"],
        promptInstructions: [
          "Run deterministic visible-behavior checks. Prefer existing project tests, screenshots, terminal capture scripts, or documented smoke commands.",
          "For McCLIM/CLIM, use Xvfb or the project's headless mode if available, capture a screenshot or log, and drive at least one basic interaction when possible.",
          "For terminal UIs, use tmux, script, pty capture, or existing terminal tests. Record artifact paths, commands, and whether visible behavior matches the invariant.",
        ],
      },
      {
        id: "review",
        kind: "CODE_REVIEW",
        title: "Review UI diff and evidence",
        description: "Review the CLIM/McCLIM/TUI diff, framework-native behavior, visible validation artifacts, and remaining UI risks.",
        descriptor: {
          stableKey: "custom.common-lisp-clim-tui.review",
          purpose: "Review the UI diff, framework-native behavior, and visible validation evidence.",
          inputs: ["UI diff", "Validation artifacts", "Visible behavior invariant"],
          outputs: ["Prioritized review findings or PASS report"],
          artifacts: ["stage report and validation evidence when produced"],
          acceptanceChecks: ["Framework-native boundaries and visible evidence are reviewed", "Remaining UI risks are reported"],
          writeScope: ["review report only"],
          isolationBoundary: ["Do not edit files during review", "Do not commit or push"],
        },
        dependsOn: ["visible-validation"],
        subagentType: "code-review-enforcer",
        sideEffects: "read",
        skills: ["common-lisp-task-graphs", "code-review", "ux-review", "common-lisp", "mcclim-manual"],
        promptInstructions: [
          "Review whether the change preserves launch paths, command/presentation or state/render boundaries, visible behavior evidence, and accessibility/usability expectations where applicable.",
          "Confirm screenshots, terminal captures, logs, commands, failures, and UI risks are summarized. Do not commit or push.",
        ],
      },
    ],
  },
} satisfies Record<string, CustomGraphSettings>;

export type PackagedCustomGraphName = keyof typeof PACKAGED_CUSTOM_GRAPH_PRESETS;

export const PACKAGED_CUSTOM_GRAPH_PRESET_NAMES = Object.keys(PACKAGED_CUSTOM_GRAPH_PRESETS) as PackagedCustomGraphName[];
