#!/usr/bin/env python3
"""Generate Kitty mappings that make XKB Meta behave like terminal Alt.

The desktop keymap keeps Meta, Alt, Super, and Hyper distinct.  Kitty identifies
those modifiers semantically, but traditional terminal programs expect the key
in XKB Mod1 (our Meta key) to use Alt's ESC-prefixed encoding.  These mappings
replace only Meta with Alt while preserving Shift, Control, Super, and Hyper.
"""

from itertools import chain, combinations
from string import ascii_lowercase, digits


CHARACTER_KEYS = (
    *ascii_lowercase,
    *digits,
    "grave",
    "minus",
    "equal",
    "left_bracket",
    "right_bracket",
    "backslash",
    "semicolon",
    "apostrophe",
    "comma",
    "period",
    "slash",
    "space",
)

# Non-ASCII characters produced by the Space Cadet Greek, typographic, and
# Top/math layers. Kitty matches shortcuts against the layout-resolved key, so
# these need explicit entries in addition to their physical base keys.
LAYER_CHARACTER_KEYS = tuple(
    "†‡▽¢○▯÷×¶≈∅θΘωΩεΕρΡτΤψΨυΥιΙοΟπΠ⟦⦃⟧⦄αΑσΣδΔφΦγΓηΗϑϴκΚλΛ"
    "¨··‖¦ζΖξΞχΧςβΒνΝμΜ«《»》∫∧∨∪∩⊂⊃∀∞∃∂⊥⊤⊢⊣↑↓←→↔⌊⌈≃≡≤≥"
)

BASIC_FUNCTION_KEYS = (
    "escape",
    "enter",
    "tab",
    "backspace",
    "insert",
    "delete",
    "left",
    "right",
    "up",
    "down",
    "page_up",
    "page_down",
    "home",
    "end",
    "caps_lock",
    "scroll_lock",
    "num_lock",
    "print_screen",
    "pause",
    "menu",
)

KEYPAD_KEYS = (
    *(f"kp_{number}" for number in range(10)),
    "kp_decimal",
    "kp_divide",
    "kp_multiply",
    "kp_subtract",
    "kp_add",
    "kp_enter",
    "kp_equal",
    "kp_separator",
    "kp_left",
    "kp_right",
    "kp_up",
    "kp_down",
    "kp_page_up",
    "kp_page_down",
    "kp_home",
    "kp_end",
    "kp_insert",
    "kp_delete",
    "kp_begin",
)

MEDIA_KEYS = (
    "media_play",
    "media_pause",
    "media_play_pause",
    "media_reverse",
    "media_stop",
    "media_fast_forward",
    "media_rewind",
    "media_track_next",
    "media_track_previous",
    "media_record",
    "lower_volume",
    "raise_volume",
    "mute_volume",
)

KEYS = tuple(
    chain(
        CHARACTER_KEYS,
        LAYER_CHARACTER_KEYS,
        BASIC_FUNCTION_KEYS,
        (f"f{number}" for number in range(1, 36)),
        KEYPAD_KEYS,
        MEDIA_KEYS,
    )
)

# Actual Alt is reserved for the window manager and is intentionally absent.
# Every combination containing Meta and terminal-visible modifiers is covered.
PASSTHROUGH_MODIFIERS = ("ctrl", "shift", "super", "hyper")
MODIFIER_COMBINATIONS = tuple(
    combination
    for count in range(len(PASSTHROUGH_MODIFIERS) + 1)
    for combination in combinations(PASSTHROUGH_MODIFIERS, count)
)


def chord(modifiers: tuple[str, ...], key: str) -> str:
    return "+".join((*modifiers, key))


def generate_mappings() -> str:
    lines = [
        "# Generated by generate-meta-as-alt.py; do not edit this output.",
        "# XKB Meta -> terminal Alt, preserving Ctrl/Shift/Super/Hyper.",
    ]
    for extra_modifiers in MODIFIER_COMBINATIONS:
        source_modifiers = ("meta", *extra_modifiers)
        target_modifiers = ("alt", *extra_modifiers)
        for key in KEYS:
            lines.append(
                f"map {chord(source_modifiers, key)} "
                f"send_key {chord(target_modifiers, key)}"
            )
    return "\n".join(lines)


if __name__ == "__main__":
    print(generate_mappings())
